import shodan
api = shodan.Shodan("rmijlWxRatPZGxTgjtYIjOWONZ2us9Wg")
s=input("enter ip adress: ")
info = api.host(s)
print('---------------------------------------------------------')
print('ip address          ==>',info['ip_str'])
print('country             ==>',end='')
print(info['country_code'],info['country_name'])
print('city                ==>',end='')
print(info['city'])
print('organization        ==>',end='')
print(info['org'])
print('open ports          ==>',end='')
print(info['ports'])
print('host names          ==>',info['hostnames'])
print('ISP                 ==>',end='')
print(info['isp'])
print('Operating System    ==>',end='')
print(info['os'])
print('latitude            ==>',end='')
print(info['latitude'])
print('longitude           ==>',end='')
print(info['longitude'])

for i in info['vulns']:
	print(i)
#print(info)
#for key in info:
	#print (key,info[key])
#print(info)
print('----------------------------------------------------------------')
